apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gharts.fullname" . }}-frontend-secrets
  labels:
    {{- include "gharts.frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  # OIDC client ID (sensitive)
  oidc-client-id: {{ .Values.frontend.config.oidc.clientId | quote }}

# Made with Bob
